DROP TABLE BOOK_LENDING;
DROP TABLE BOOK_COPIES;
DROP TABLE BOOK_AUTHORS;
DROP TABLE BOOK;
DROP TABLE LIBRARY_PROGRAMME;
DROP TABLE PUBLISHER;



CREATE TABLE PUBLISHER (
    Name VARCHAR(50) PRIMARY KEY,
    Address VARCHAR(100),
    Phone VARCHAR(15)
);
CREATE TABLE BOOK (
    Book_id INT PRIMARY KEY,
    Title VARCHAR(100),
    Publisher_Name VARCHAR(50),
    Pub_Year INT,
    FOREIGN KEY (Publisher_Name) REFERENCES PUBLISHER(Name)
);
CREATE TABLE BOOK_AUTHORS (
    Book_id INT,
    Author_Name VARCHAR(50),
    PRIMARY KEY (Book_id, Author_Name),
    FOREIGN KEY (Book_id) REFERENCES BOOK(Book_id)
);
CREATE TABLE LIBRARY_PROGRAMME (
    Programme_id INT PRIMARY KEY,
    Programme_Name VARCHAR(50),
    Address VARCHAR(100)
);
CREATE TABLE BOOK_COPIES (
    Book_id INT,
    Programme_id INT,
    No_of_Copies INT,
    PRIMARY KEY (Book_id, Programme_id),
    FOREIGN KEY (Book_id) REFERENCES BOOK(Book_id),
    FOREIGN KEY (Programme_id) REFERENCES LIBRARY_PROGRAMME(Programme_id)
);
CREATE TABLE BOOK_LENDING (
    Book_id INT,
    Programme_id INT,
    Card_No INT,
    Date_Out DATE,
    Due_Date DATE,
    PRIMARY KEY (Book_id, Programme_id, Card_No, Date_Out),
    FOREIGN KEY (Book_id) REFERENCES BOOK(Book_id),
    FOREIGN KEY (Programme_id) REFERENCES LIBRARY_PROGRAMME(Programme_id)
);
INSERT INTO PUBLISHER VALUES ('Pearson', 'Bangalore', '9876543210');
INSERT INTO PUBLISHER VALUES ('McGrawHill', 'Delhi', '9123456780');
INSERT INTO PUBLISHER VALUES ('Oxford', 'Mumbai', '9988776655');
INSERT INTO PUBLISHER VALUES ('Cambridge', 'Chennai', '9090909090');
INSERT INTO PUBLISHER VALUES ('Wiley', 'Hyderabad', '9001122334');
INSERT INTO PUBLISHER VALUES ('Springer', 'Pune', '9112233445');

INSERT INTO BOOK VALUES (101, 'Database Systems', 'Pearson', 2015);
INSERT INTO BOOK VALUES (102, 'Operating System', 'McGrawHill', 2017);
INSERT INTO BOOK VALUES (103, 'Computer Networks', 'Oxford', 2012);
INSERT INTO BOOK VALUES (104, 'Data Structures', 'Cambridge', 2010);
INSERT INTO BOOK VALUES (105, 'Machine Learning', 'Wiley', 2020);
INSERT INTO BOOK VALUES (106, 'Artificial Intelligence', 'Springer', 2018);

INSERT INTO BOOK_AUTHORS VALUES (101, 'Navathe');
INSERT INTO BOOK_AUTHORS VALUES (102, 'Silberschatz');
INSERT INTO BOOK_AUTHORS VALUES (103, 'Tanenbaum');
INSERT INTO BOOK_AUTHORS VALUES (104, 'Seymour Lipschutz');
INSERT INTO BOOK_AUTHORS VALUES (105, 'Tom Mitchell');
INSERT INTO BOOK_AUTHORS VALUES (106, 'Stuart Russell');


INSERT INTO LIBRARY_PROGRAMME VALUES (1, 'CSE', 'Block A');
INSERT INTO LIBRARY_PROGRAMME VALUES (2, 'ISE', 'Block B');
INSERT INTO LIBRARY_PROGRAMME VALUES (3, 'ECE', 'Block C');
INSERT INTO LIBRARY_PROGRAMME VALUES (4, 'EEE', 'Block D');
INSERT INTO LIBRARY_PROGRAMME VALUES (5, 'MECH', 'Block E');
INSERT INTO LIBRARY_PROGRAMME VALUES (6, 'CIVIL', 'Block F');

INSERT INTO BOOK_COPIES VALUES (101, 1, 10);
INSERT INTO BOOK_COPIES VALUES (102, 2, 8);
INSERT INTO BOOK_COPIES VALUES (103, 3, 6);
INSERT INTO BOOK_COPIES VALUES (104, 4, 7);
INSERT INTO BOOK_COPIES VALUES (105, 5, 5);
INSERT INTO BOOK_COPIES VALUES (106, 6, 9);


INSERT INTO BOOK_LENDING VALUES (101, 1, 501, '2017-01-10', '2017-01-25');
INSERT INTO BOOK_LENDING VALUES (102, 2, 502, '2017-02-15', '2017-03-01');
INSERT INTO BOOK_LENDING VALUES (103, 3, 503, '2017-03-05', '2017-03-20');
INSERT INTO BOOK_LENDING VALUES (104, 4, 504, '2017-04-12', '2017-04-27');
INSERT INTO BOOK_LENDING VALUES (105, 5, 505, '2017-05-08', '2017-05-23');
INSERT INTO BOOK_LENDING VALUES (106, 6, 506, '2017-06-18', '2017-07-03');

 select *,No_of_Copies from Book b,Book_copies c where b.book_id=c.book_id;

SELECT b.card_no
FROM book_lending b
WHERE b.date_out BETWEEN '2017-01-10' AND '2017-03-10' GROUP BY b.card_no
HAVING COUNT(b.card_no) > 1;

create table book_2017 select  * from book where pub_year ="2017";

